modLoader="javafml"
loaderVersion="[31,)"

issueTrackerURL="https://github.com/MrCrayfish/ImprovedWolves/issues"

[[mods]]
modId="improvedwolves"
version="1.0.0"
displayName="Improved Wolves"
updateJSONURL=""
displayURL="https://mrcrayfish.com/mods?id=improvedwolves"
logoFile="examplemod.png"
credits="@Rexxgamesss and @Jor02video on Twitter for ideas"
authors="MrCrayfish"
description='Makes wolves smarter!'

[[dependencies.improvedwolves]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.improvedwolves]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
